# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/ssys/repos/git_personal/terragrunt-local-example/deployment/variables/myaccount/us-east-1/test_vpc/tg_module/terraform.tfstate"
  }
}
